### ISSUE TITLE
PATCH /users/:id

### ISSUE THREAD

**Issue by omar-dahdouh** [GSG-G8/room-booker#21]
### Description
edits profile (display name, email, active)

#### Request body:
```javascript
{
   name,
   email,
   active,
}
```

#### Validation
```javascript
{
   name: string.min(3),
   email: email
   active: boolean
}
```

**Comment by Amoodaa** [comment]
Okay to make it clearer, basically this route will need to be able to edit the following:
is active, is admin (admin only)
everything else, (owner and admin)
