### ISSUE TITLE
👋 Introduction

### ISSUE THREAD

**Issue by okjake** [GSG-G8/room-booker#69]
Hi all!

I'm Jake, I'll be helping out with some code reviewing. You can get me on discord (Jake~) if you have any questions or would like to set up some time to chat more generally 🙂

The code is looking good! Is there a version deployed to Heroku or similar? Or if you can commit a version of the .env file _with all of the secrets removed_ as .env.template or similar, I can set up the relevant services and run it locally

**Comment by LinaYahya** [comment]
@okjake  Hi Jake, 
I'm Lina, one of the team members, looking forward to seeing your review.

**Comment by Amoodaa** [comment]
I've sent you on discord some instructions, check them when you get online

**Comment by okjake** [comment]
Thanks!
