### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by okjake** [GSG-G8/room-booker#78]
Hi all!

I've done an initial review of the code as of this morning. In general it's looking great.
I have some suggestions for enhancements and next steps, as well as areas I'd suggest you research for next time. You can see the details here:

https://github.com/okjake/room-booker/pull/1

If you have any questions or comments at any point you can leave them here or get me on discord or jakepyne@gmail.com

Keep up the good work!

**Comment by Amoodaa** [comment]
Really thanks for this long list of suggestions 👌
We are going to take a week's break, then 2 weeks of react, then are going to refactor, and we will try to address as much of these issues as we possibly can
Thank you so much!

**Comment by okjake** [comment]
Great! No problem.
Don't feel that you have to address everything, and let me know if anything's unclear.
